os: osx
osx_image: xcode9.2
language: objective-c
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT_FRAMEWORK=NOCReachabilityFramework/NOCReachabilityFramework.xcworkspace
    - SCHEME_FRAMEWORK=NOCReachabilityFramework
    - SCHEME_UNIVERSAL=UniversalFramework
    - PROJECT_DEMO=Demo/NOCReachability-Demo.xcworkspace
    - SCHEME_LIBRARY_DEMO=NOCReachability-Demo
    - SCHEME_FRAMEWORK_DEMO=NOCReachabilityFramework-Demo
    - IOS_SDK=iphonesimulator11.1
    - CONFIG_DEBUG="Debug"
    - CONFIG_RELEASE="Release"
  matrix:
    - POD_LINT="YES"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_FRAMEWORK"      SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_FRAMEWORK"      SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_UNIVERSAL"      SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_FRAMEWORK" SCHEME="$SCHEME_UNIVERSAL"      SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_LIBRARY_DEMO"   SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_LIBRARY_DEMO"   SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_FRAMEWORK_DEMO" SDK="$IOS_SDK"  CONFIG="$CONFIG_DEBUG"
    - POD_LINT="NO" PROJECT_FILE="$PROJECT_DEMO"      SCHEME="$SCHEME_FRAMEWORK_DEMO" SDK="$IOS_SDK"  CONFIG="$CONFIG_RELEASE"
before_install:
  - brew update
  - gem install xcpretty
  - brew install cocoapods
script:
  - set -o pipefail

  - if [ $POD_LINT == "YES" ]; then pod lib  lint; fi
  - if [ $POD_LINT == "YES" ]; then pod spec lint; fi

  - if [ $POD_LINT == "NO" ]; then xcodebuild -version;  fi
  - if [ $POD_LINT == "NO" ]; then xcodebuild -showsdks; fi
  - if [ $POD_LINT == "NO" ]; then xcrun simctl list;    fi

  - if [ $PROJECT_FILE == "$PROJECT_FRAMEWORK" ]; then cd NOCReachabilityFramework; pod install; cd ../; fi
  - if [ $PROJECT_FILE == "$PROJECT_DEMO"      ]; then cd Demo;                     pod install; cd ../; fi

  - if [ $POD_LINT == "NO" ]; then xcodebuild -workspace "$PROJECT_FILE" -scheme "$SCHEME" -configuration "$CONFIG" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c; fi
